pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = '1' // Reemplaza con el ID de las credenciales que creaste en Jenkins
        registryCredential = 'dockerhub-credentials-id' // Reemplaza con el ID de las credenciales de DockerHub
    }

    stages {
        stage('Clonar Repositorio') {
            steps {
                // Clonar el repositorio de GitHub donde tienes tus archivos de configuración
                git url: 'https://github.com/matLord314/t3.git', credentialsId: env.GIT_CREDENTIALS_ID
            }
        }

        stage('Construir Imágenes Docker') {
            parallel {
                stage('Construir Imagen w1') {
                    steps {
                        script {
                            // Construir la imagen Docker para w1
                            docker.build('w1_image_jenkin_kub', './t2-master/t2-master/w1')
                        }
                    }
                }
                stage('Construir Imagen w2') {
                    steps {
                        script {
                            // Construir la imagen Docker para w2
                            docker.build('w2_image_jenkin_kub', './t2-master/t2-master/w2')
                        }
                    }
                }
                stage('Construir Imagen Reverse Proxy') {
                    steps {
                        script {
                            // Construir la imagen Docker para el reverse proxy
                            docker.build('rp_image_jenkin_kub', './t2-master/t2-master/rprr')
                        }
                    }
                }
            }
        }

        stage('Subir Imágenes Docker') {
            steps {
                script {
                    def tag = "stable-${env.BUILD_ID}"
                    withCredentials([usernamePassword(credentialsId: env.registryCredential, passwordVariable: 'DOCKERHUB_PWD', usernameVariable: 'DOCKERHUB_USER')]) {
                        docker.withRegistry('https://index.docker.io/v1/', env.registryCredential) {
                            sh "docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PWD}"
                        
                            // Etiquetado y subida de imágenes
                            sh "docker tag w1_image_jenkin_kub:latest matlord/w1_image_jenkin_kub:${tag}"
                            sh "docker tag w2_image_jenkin_kub:latest matlord/w2_image_jenkin_kub:${tag}"
                            sh "docker tag rp_image_jenkin_kub:latest matlord/rp_image_jenkin_kub:${tag}"

                            sh "docker push matlord/w1_image_jenkin_kub:${tag}"
                            sh "docker push matlord/w2_image_jenkin_kub:${tag}"
                            sh "docker push matlord/rp_image_jenkin_kub:${tag}"
                        }
                    }
                }
            }
        }

        stage('Actualizar y Desplegar en Kubernetes') {
            steps {
                script {
                    def yamlPath = '/tmp/config-copy' // Ruta en la máquina del clúster donde están los archivos YAML
                    def tag = "stable-${env.BUILD_ID}" // Usar el mismo tag que se utilizó para empujar las imágenes

                    // Verificar que los archivos existen
                    sh "ls -l ${yamlPath}"

                    // Actualizar el placeholder en los archivos YAML
                    sh "sed -i 's|__IMAGE_TAG__|${tag}|' ${yamlPath}/w1-deployment.yaml"
                    sh "sed -i 's|__IMAGE_TAG__|${tag}|' ${yamlPath}/w2-deployment.yaml"
                    sh "sed -i 's|__IMAGE_TAG__|${tag}|' ${yamlPath}/rprr-deployment.yaml"

                    // Verificar que los placeholders fueron reemplazados correctamente
                    sh "cat ${yamlPath}/w1-deployment.yaml"
                    sh "cat ${yamlPath}/w2-deployment.yaml"
                    sh "cat ${yamlPath}/rprr-deployment.yaml"

                    // Aplicar los archivos YAML en el clúster de Kubernetes
                    sh "kubectl apply -f ${yamlPath}/w1-deployment.yaml"
                    sh "kubectl apply -f ${yamlPath}/w2-deployment.yaml"
                    sh "kubectl apply -f ${yamlPath}/rprr-deployment.yaml"
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
